name: kadi_server
description: A high-performance WebSocket game server.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.7
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  mailer: ^6.1.0
  sqlite3: ^2.3.0
  dbcrypt: ^2.0.0
  dart_jsonwebtoken: ^2.4.2
  shelf_static: ^1.1.2
  shelf_multipart: ^0.1.0+1
